$ErrorActionPreference = "Stop"

$repoRoot = Split-Path $PSScriptRoot -Parent
$sourcesPath = Join-Path $repoRoot "sources.json"
$assetsRoot = Join-Path $repoRoot "assets"
$maxBytes = 95MB

if (!(Test-Path $sourcesPath)) {
  throw "sources.json not found"
}

$sources = Get-Content -Raw -Path $sourcesPath | ConvertFrom-Json
New-Item -ItemType Directory -Force -Path $assetsRoot | Out-Null

$report = @()
$index = @()

foreach ($folder in $sources.folders) {
  $target = Join-Path $assetsRoot $folder.slug
  New-Item -ItemType Directory -Force -Path $target | Out-Null

  Write-Host "Syncing $($folder.title)"
  Write-Host "Source: $($folder.drive_url)"

  $before = @(Get-ChildItem -Path $target -Recurse -File -ErrorAction SilentlyContinue)

  try {
    gdown --folder $folder.drive_url --output $target --remaining-ok --continue
  } catch {
    Write-Warning "gdown failed for $($folder.title): $($_.Exception.Message)"
  }

  $removed = @()
  Get-ChildItem -Path $target -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.Length -gt $maxBytes) {
      $removed += [pscustomobject]@{ path = $_.FullName.Replace($repoRoot + [IO.Path]::DirectorySeparatorChar, ""); size = $_.Length }
      Remove-Item -LiteralPath $_.FullName -Force
    }
  }

  $after = @(Get-ChildItem -Path $target -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Name -ne ".gitkeep" })

  foreach ($file in $after) {
    $relative = $file.FullName.Replace($repoRoot + [IO.Path]::DirectorySeparatorChar, "").Replace("\\", "/")
    $index += [pscustomobject]@{
      source_title = $folder.title
      source_slug = $folder.slug
      path = $relative
      name = $file.Name
      size = $file.Length
      extension = $file.Extension.TrimStart('.').ToLowerInvariant()
    }
  }

  $report += [pscustomobject]@{
    title = $folder.title
    slug = $folder.slug
    source = $folder.drive_url
    files_before = $before.Count
    files_after = $after.Count
    removed_large_files = $removed.Count
  }
}

$index | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-Path $repoRoot "asset-index.json") -Encoding UTF8

$lines = @()
$lines += "# Sync report"
$lines += ""
$lines += "Generated by GitHub Actions."
$lines += ""
$lines += "| Folder | Files | Source |"
$lines += "|---|---:|---|"
foreach ($entry in $report) {
  $lines += "| $($entry.title) | $($entry.files_after) | $($entry.source) |"
}
$lines += ""
$lines += "Files above 95 MB are skipped to stay below GitHub's hard file-size limit."
$lines | Set-Content -Path (Join-Path $repoRoot "sync-report.md") -Encoding UTF8

Write-Host "Synced $($index.Count) files into assets/."
